//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSN
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Categories_Articles = new HashSet<Categories_Articles>();
            this.Sources = new HashSet<Source>();
        }
    
        public int ID_Article { get; set; }
        public string Name_Article { get; set; }
        [AllowHtml]
        public string Discription_Article { get; set; }
        public string Image_Article { get; set; }
        public System.DateTime CreationDate_Article { get; set; }
        public Nullable<int> Writer_ID { get; set; }
        public string Discript { get; set; }
    
        public virtual Writer Writer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories_Articles> Categories_Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Source> Sources { get; set; }
    }
}
