//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories_Articles
    {
        public int Category_ID { get; set; }
        public int Article_ID { get; set; }
        public string Creationdate_Article { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Category_Article Category_Article { get; set; }
    }
}
