//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Lessons
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Order_Number { get; set; }
        public string PDF { get; set; }
        public string Type { get; set; }
        public int Unit_Id { get; set; }
        public Nullable<int> Group_Id { get; set; }
    
        public virtual Course_units Course_units { get; set; }
        public virtual Group Group { get; set; }
    }
}
