//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoursesDBEntities : DbContext
    {
        public CoursesDBEntities()
            : base("name=CoursesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Categories_Articles> Categories_Articles { get; set; }
        public virtual DbSet<Certification> Certifications { get; set; }
        public virtual DbSet<Course_Lessons> Course_Lessons { get; set; }
        public virtual DbSet<Course_units> Course_units { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Courses_Name> Courses_Name { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Students_Groups> Students_Groups { get; set; }
        public virtual DbSet<Trainee> Trainees { get; set; }
        public virtual DbSet<Trainee_courses> Trainee_courses { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<Trainer_Courses> Trainer_Courses { get; set; }
        public virtual DbSet<Writer> Writers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Category_Article> Category_Article { get; set; }
        public virtual DbSet<Gallery_Image> Gallery_Image { get; set; }
        public virtual DbSet<Gallery_Testimonial> Gallery_Testimonial { get; set; }
        public virtual DbSet<Gallery_Video> Gallery_Video { get; set; }
    }
}
