//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPSN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer_Courses
    {
        public int Trainer_ID { get; set; }
        public int Course_ID { get; set; }
        public string Creation_date { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
